year: '2019'
min_size: 1000000
geojson: /home/kyle/NRML/data/perims/
output: /home/kyle/NRML/data/tiff/
drive_dir: EarthEngine_WildfireSpreadTS_2020
credentials: /home/kyle/NRML/OAuth/credentials.json
project_id: ee-earthdata-459817
download: false
export_data: false
show_config: true
force_new_geojson: true
sync_year: false
