year: '2019'
min_size: 1000000
geojson_dir: /home/kyle/NRML/data/perims/
output: /home/kyle/NRML/data/tiff/2019/
drive_dir: EarthEngine_WildfireSpreadTS_2019
credentials: /home/kyle/NRML/OAuth/credentials.json
project_id: ee-earthdata-459817
download: false
export_data: true
show_config: true
force_new_geojson: true
sync_year: true
