project_id: ee-earthdata-459817
data_dir: /home/kyle/ee_wildfire_data
credentials: /home/kyle/ee_wildfire_data/OAuth/credentials.json
year: '2005'
month: '1'
geojson_dir: /home/kyle/ee_wildfire_data/perims
tiff_dir: /home/kyle/ee_wildfire_data/tiff/2005
drive_dir: EarthEngine_WildfireSpreadTS_2005
download: false
export: false
force_new_geojson: false
min_size: 10000000
